spring:
  application:
    name: Jessy Security
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    url: ${DB_URL}
    user: ${DB_MIGRATION_USER}
    password: ${DB_MIGRATION_PASSWORD}
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true


server:
  port: 3000
  servlet:
    context-path: /api

