
ALTER ROLE master WITH PASSWORD 'secret';

CREATE DATABASE jessy_security;

CREATE ROLE rivas WITH LOGIN PASSWORD 'secret' CREATEDB CREATEROLE NOSUPERUSER NOREPLICATION;
GRANT ALL PRIVILEGES ON DATABASE jessy_security TO rivas;
ALTER DATABASE jessy_security OWNER TO rivas;

ALTER ROLE rivas WITH PASSWORD 'secret';
