CREATE ROLE api_client WITH LOGIN PASSWORD 'secret';

-- PERMISOS API_CLIENT
GRANT CONNECT ON DATABASE jessy_security to api_client;
GRANT USAGE ON SCHEMA public TO api_client;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO api_client;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO api_client;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_client;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO api_client;

ALTER ROLE api_client WITH PASSWORD 'secret';

-- REVOCAR PERMISOS
REVOKE SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
    FROM api_client;
REVOKE USAGE, SELECT
    ON ALL SEQUENCES IN SCHEMA public
    FROM api_client;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE
    ON TABLES FROM api_client;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE USAGE, SELECT
    ON SEQUENCES FROM api_client;