CREATE TABLE notices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message    VARCHAR(300)                             NOT NULL,
    created_at TIMESTAMPTZ                              NOT NULL,
    CONSTRAINT pk_notices PRIMARY KEY (id)
);